- id: golangci-lint
  name: "golangci-lint"
  entry: ./.pre-commit/run-golangci-lint.sh
  types: [go]
  language: "script"
  pass_filenames: false
  description: "Runs `golangci-lint run ./...`, requires https://github.com/golangci/golangci-lint"

- id: golangci-fmt
  name: "golangci-fmt"
  entry: ./.pre-commit/run-golangci-fmt.sh
  types: [go]
  language: "script"
  pass_filenames: false
  description: "Runs `golangci-lint fmt ./...`, requires https://github.com/golangci/golangci-lint"

- id: go-unit-tests
  name: "go-unit-tests"
  entry: ./.pre-commit/run-go-unit-tests.sh
  files: '\.go$'
  language: "script"
  description: "Runs `go test`"
